# Generated by Django 6.0.7 on 2026-09-16 13:17

import uuid
from django.db import migrations, models


def fill_map_numbers(apps, schema_editor):
    Profile = apps.get_model('core', 'Profile')
    used = set()
    for profile in Profile.objects.all().order_by('id'):
        number = uuid.uuid4().hex[:10].upper()
        while number in used:
            number = uuid.uuid4().hex[:10].upper()
        profile.map_number = number
        profile.save(update_fields=['map_number'])
        used.add(number)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='map_number',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.RunPython(fill_map_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='map_number',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, unique=True),
        ),
    ]
